#!/usr/bin/env bash

APP_NAME_PAHELPER="pulseaudio-helper"
APP_VERSION="${APP_VERSION:-0.4}"

## options to be passed from calling function
OPT_STOP_PULSEAUDIO="${OPT_STOP_PULSEAUDIO:-}"
OPT_DISABLE_PULSEAUDIO="${OPT_DISABLE_PULSEAUDIO:-}"

## strings for pulseaudio handling
CMD_PULSEAUDIO="${CMD_PULSEAUDIO:-}"
PA_CLIENT_USER_CONF_FALLBACKPATH=${HOME}/.pulse/client.conf
PA_CLIENT_USER_CONF_PATH=${HOME}/.config/pulse/client.conf
PA_CLIENT_SYSTEM_CONF_PATH=/etc/pulse/client.conf
PA_CLIENT_CONF=""
MSG_PA_CONFFILE="pulseaudio user configuration file"
PACLIENT_CONF_MODIFIED=""
PA_CLIENT_PID=""
PA_CLIENT_CONF_BACKUP=""

## helper script for mpd-configure to control pulseaudio
function echo_stderr() {
    printf "%s\n" "$@" 1>&2; 
}

function die() {
    echo_stderr "\nError in ${APP_NAME_PAHELPER} (v${APP_VERSION}): $@"
    exit 1
}

function debug_pahelper() {
    echo_stderr "DEBUG ${APP_NAME_PAHELPER} *** $@"    
}

function debug_function() {
    printf "DEBUG %-18s:\n" "${APP_NAME_PAHELPER}" 1>&2;
    printf "\tentering function \`%s',\n" "$1" 1>&2;
    printf "\twith arguments \`%s'\n" "$2" 1>&2;
}

function inform() {
    echo_stderr "$@\n"
}


function paclient_restore_clientconf() {
    ## restore backed up client configuration if created by script.
    ## TODO: check neccessity and/or cleanup
    [[ ! -z ${DEBUG} ]] && \
	debug_function "${FUNCNAME}" "$*"

    if [[ -f "${PA_CLIENT_CONF_BACKUP}" ]]; then
	res="$(cp -av "${PA_CLIENT_CONF_BACKUP}" "${PA_CLIENT_CONF}")"
	if [[ $? -ne 0 ]]; then
	    ## error restoring
	    ## TODO: make fatal?
	    printf "Could not restore original %s \`%s'.\n" \
		   "${MSG_PA_CONFFILE}" "${PA_CLIENT_CONF}"
	    printf "Backup created in \`%s'." \
		   "${PA_CLIENT_CONF_BACKUP}"
	    return 1
	else
	    ## succesfully copied backup conf to client.conf
	    [[ ! -z "${DEBUG}" ]] && \
		debug_pahelper \
		    "${MSG_PA_CONFFILE} \`${PA_CLIENT_CONF_BACKUP}' \
successfully restored to \`${PA_CLIENT_CONF}'."
	    ## remove the backup
	    res="$(rm "${PA_CLIENT_CONF_BACKUP}")"
	    if [[ $? -ne 0 ]]; then
		[[ ! -z "${DEBUG}" ]] && \
		    debug_pahelper "${FUNCNAME}: removal of ${MSG_PA_CONFFILE} \
 \`${PA_CLIENT_CONF_BACKUP}' failed with error: \`${res}'."
		return 1
	    else
		[[ ! -z "${DEBUG}" ]] && \
		    debug_pahelper "${FUNCNAME}: backup ${MSG_PA_CONFFILE} \
 \`${PA_CLIENT_CONF_BACKUP}' successfully removed."
		return 0
	    fi
	fi
    fi

}


function check_paclient_stopped() {
    ## returns nothing or error with pid of pulseaudio if it is running
    [[ ! -z ${DEBUG} ]] && \
	debug_function "${FUNCNAME}" "$*"

    PA_CLIENT_PID="$1"
    res="$(ps -fp "${PA_CLIENT_PID}")"
    if [[ $? -ne 0 ]]; then
	[[ ! -z "${DEBUG}" ]] && \
	    debug_pahelper "${FUNCNAME}: pulseaudio is not running"
	return 1
    else
	## return its pid
	[[ ! -z "${DEBUG}" ]] && \
	    debug_pahelper "${FUNCNAME}: pulseaudio is running: \`${PA_CLIENT_PID}'"
	printf "%s" "${PA_CLIENT_PID}"
    fi
}

function paclient_start() {
    ## start pulseaudio
    ## TODO: check neccessity and/or cleanup
    [[ ! -z ${DEBUG} ]] && \
	debug_function "${FUNCNAME}" "$*"
    
    if [[ ! -z "$(check_paclient_stopped)" ]]; then
	## pulseaudio is running
	[[ ! -z "${DEBUG}" ]] && \
	    debug_pahelper "${FUNCNAME}: not starting pulseaudio, is already running."
    else
	## pulseaudio is not running, start it
	res=$(${CMD_PULSEAUDIO} --start)
	if [[ ! -z "$(check_paclient_stopped)" ]]; then	
	    [[ ! -z "${DEBUG}" ]] && debug_pahelper "${FUNCNAME}: pulseaudio started."
	else
	    [[ ! -z "${DEBUG}" ]] && debug_pahelper "${FUNCNAME}: pulseaudio could not be started."
	fi
    fi

}


function paclient_disable_respawn() {
    ## disables spawning of pulseaudio
    ## TODO: check neccessity and/or cleanup
    [[ ! -z ${DEBUG} ]] && \
	debug_function "${FUNCNAME}" "$*"

    ## create or overwrite the pulseaudio configuration file
    if [[ ! -f "${PA_CLIENT_USER_CONF_PATH}" ]]; then
	[[ ! -z ${DEBUG} ]] && \
	    debug_pahelper "${FUNCNAME}: no ${MSG_PA_CONFFILE} found."
    else
	[[ ! -z ${DEBUG} ]] && \
	    debug_pahelper "${FUNCNAME}: \
 ${MSG_PA_CONFFILE} file found: \`${PA_CLIENT_USER_CONF_PATH}'."
	PA_CLIENT_CONF_BACKUP="$(paclient_backup_clientconf \
"${PA_CLIENT_USER_CONF_PATH}")"
	if [[ $? -ne 0 ]]; then
	    return 1
	else
	    res="$(printf "autospawn=no\n" > "${PA_CLIENT_USER_CONF_PATH}")"
	    if [[ $? -ne 0 ]]; then
		[[ ! -z "${DEBUG}" ]] && \
		    debug_pahelper "${FUNCNAME}: creating ${MSG_PA_CONFFILE} \
 \`${PA_CLIENT_USER_CONF_PATH}' failed with error: \`${res}'."
		return 1
	    else
		[[ ! -z "${DEBUG}" ]] && \
		    debug_pahelper "${FUNCNAME}: respawning disabled by creating \
${MSG_PA_CONFFILE} \`${PA_CLIENT_USER_CONF_PATH}'."
		return 0
	    fi
	fi	    
    fi
}


function paclient_backup_clientconf() {
    ## backs up client.conf, returns path to backup conf file on
    ## success, 1 on error.
    ## TODO: check neccessity and/or cleanup
    [[ ! -z ${DEBUG} ]] && \
	debug_function "${FUNCNAME}" "$*"

    PA_CLIENT_CONF="$1"
    PA_CLIENT_CONF_BACKUP="${PA_CLIENT_CONF}.backup-$$"
    res="$(cp -av "${PA_CLIENT_CONF}" "${PA_CLIENT_CONF_BACKUP}" 2>&1)"
    if [[ $? -ne 0 ]]; then
	[[ ! -z "${DEBUG}" ]] && \
	    debug_pahelper "${FUNCNAME}: could not create a backup of ${MSG_PA_CONFFILE} \
\`${PA_CLIENT_CONF}' to \`${PA_CLIENT_CONF_BACKUP}. \
failed with error: \`${res}'."
	return 1
    else 
	[[ ! -z "${DEBUG}" ]] && \
	    debug_pahelper "${FUNCNAME}: ${MSG_PA_CONFFILE} \`${PA_CLIENT_CONF}' \
backed up to \`${PA_CLIENT_CONF_BACKUP}'."
	printf "${PA_CLIENT_CONF_BACKUP}"
	return 0
    fi
}


function paclient_stop() {
    ## stop pulseaudio instance by killing the PID indicated in $1 and
    ## temporary or permanently keeping it from respawning.
    ## afterwards, check if it is really stopped.
    ## returns 0 or error 1 with description
    [[ ! -z ${DEBUG} ]] && \
	debug_function "${FUNCNAME}" "$*"

    PA_CLIENT_PID="$1"

    ## disable respawning of the daemon
    paclient_disable_respawn
    if [[ $? -ne 0 ]]; then
	msg="unable to keep pulseaudio from respawning"
	[[ ! -z ${DEBUG} ]] && debug_pahelper "${FUNCNAME}: ${msg}"
	printf "%s" "${msg}"
	return 1
    else
	## respawning temporary disabled
	## kill pulseaudio
	res=$(${CMD_PULSEAUDIO} -vv --kill)
	reskill="$?"
	sleep 1s
	if [[ ${reskill} -ne 0 ]]; then
	    msg="pulseaudio --kill failed to stop PID ${PA_CLIENT_PID} with return code \`${res}'."
	    [[ ! -z ${DEBUG} ]] && debug_pahelper "${FUNCNAME}: ${msg}"
	    ## try killing it by its pid
	    res="$(kill -9 ${PA_CLIENT_PID})"
	    reskill="$?"
	    sleep 1s
	    if [[ $? -ne 0 ]]; then
		msg="unable to kill pulseaudio by sending SIGTERM to its PID."
		[[ ! -z ${DEBUG} ]] && debug_pahelper "${FUNCNAME}: ${msg}"
		printf "%s" "${msg}"
		return 1
	    else
		[[ ! -z ${DEBUG} ]] && \
		    debug_pahelper "${FUNCNAME}: sending SIGTERM to its PID  \
succesfully stopped the pulseaudio client with PID ${PA_CLIENT_PID}'."
	    fi
	else
	    [[ ! -z ${DEBUG} ]] && \
		debug_pahelper "${FUNCNAME}: \`pulseaudio --kill' \
succesfully stopped the pulseaudio client with PID ${PA_CLIENT_PID}."
	fi
	## wait for pulseaudio to exit check if that worked
	if [[ -z "$(check_paclient_stopped "${PA_CLIENT_PID}")" ]]; then
	    [[ ! -z "${DEBUG}" ]] && \
	     	debug_pahelper "${FUNCNAME}: pulseaudio is definitely killed."
	    return 0
	else
	    msg="pulseaudio respawned. ${MSG_ERROR_UNEXPECTED}."
	    [[ ! -z "${DEBUG}" ]] && \
	     	    debug_pahelper "${FUNCNAME}: pulseaudio respawned. ${MSG_ERROR_UNEXPECTED}."
	    printf "%s" "${msg}"
	    return 1

	fi
    fi
    
}


